### ISSUE TITLE
Bug Abuse

### ISSUE THREAD

**Issue by ChrizsTTV** [MAtiyaaa/qb-policelockers#1]
Hey there Is a mighty flaw in that whole script. Cops could just open their own lockers everywhere filled with like 100 armors and would never run outta ammo

**Comment by MAtiyaaa** [comment]
True. 
Would probably be best if I implement that cops can only access the locker when they're in the station? (or wherever defined in config)
Or I can add banned items that can't be placed in a locked?
I might go for the first one.

**Comment by ChrizsTTV** [comment]
Yea maybe add like a target that opens a qb-input menu where you enter the ID for the locker or like you said only in specific areas

**Comment by MAtiyaaa** [comment]
Will work on both options

**Comment by MAtiyaaa** [comment]
Done
